#!/bin/bash

CUR_BRANCH=$(git symbolic-ref -q --short HEAD)
OUT_FILE='/tmp/fetch-dev-out'

# if current branch is dev just pull
if [[ $CUR_BRANCH == 'develop' ]];
then
	git pull;
	exit;
fi

git checkout develop 2> $OUT_FILE

# if error on checkout abort
if [[ $(cat $OUT_FILE) == error:* ]];
then
	cat $OUT_FILE | ghead -n -1;
	echo "Aborting fetch-dev.";
	exit;
fi

git pull
git checkout $CUR_BRANCH
