#!/bin/bash
if [[ ! $(git rev-parse --git-dir 2> /dev/null) ]];
then
	echo 'Current working directory is not a git repository.';
	exit 1;
fi

BRANCH=$(git symbolic-ref --short -q HEAD)

git push --set-upstream origin "$BRANCH:<my-name>/$BRANCH"

git cpbranch >/dev/null
echo "<my-name>/$(pbpaste)" | pbcopy
echo "Copied branch name '<my-name>/$BRANCH' to clipboard!"

